name: BukkitExamplePlugin
version: 1.0
api-version: 1.15
main: zemian.minecraft.bukkitexampleplugin.broadcast.ExamplePlugin

commands:
  hello:
    description: My First Hello World Minecraft Plugin.
